# Generated by Django 5.1.1 on 2024-09-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0002_statut_product_datefabrication_product_prixht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='statut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LesProduits.statut'),
            preserve_default=False,
        ),
    ]
